media:
  input: assets/images
  output: /assets/images

content:
  - name: posts
    label: 文章管理
    type: collection
    path: _posts
    format: yaml-frontmatter

    filename:
      template: "{year}-{month}-{day}-{title}.md"
      field: false

    view:
      fields:
        - title
        - date
        - published
      primary: title
      sort:
        - date
        - title
      default:
        sort: date
        order: desc

    fields:
      - name: layout
        label: 页面模板
        type: string
        default: post
        hidden: true

      - name: title
        label: 文章标题
        type: string
        required: true

      - name: date
        label: 发布日期
        type: date
        required: true
        options:
          format: yyyy-MM-dd

      - name: categories
        label: 分类
        type: string

      - name: tags
        label: 标签
        type: string

      - name: description
        label: SEO 描述
        type: text

      - name: published
        label: 是否发布
        type: boolean
        default: true

      - name: body
        label: 文章正文
        type: rich-text
        required: true
        options:
          format: markdown
          switcher: true
